# Permalinks
permalink:           pretty

# Setup
title:               Arthur's site
url:                 http://za-arthur.github.io
baseurl:             ""

excerpt_separator: <!--more-->

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Arthur
  github:            https://github.com/za-arthur
  twitter:           https://twitter.com/za_arthur

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/za-arthur/za-arthur.github.io
