# Permalinks
permalink:           pretty

# Setup
title:               Arthur's blog
url:                 http://select-artur.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Arthur
  url:               https://github.com/select-artur

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/select-artur/select-artur.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
